<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ScudProvisioner.Cli</RootNamespace>
    <AssemblyName>scud-provision</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScudProvisioner.Core\ScudProvisioner.Core.csproj" />
  </ItemGroup>

</Project>
